### PR TITLE
Quick fix for SpokenLanguages in ManagerDashboard

### PR DESCRIPTION
**Pull request by AlexVDV116**
A quick fix where the SpokenLanguages has been added to the UpdateMovieDto and AddMovieDto. 
The UI in the ManagerDashboard has also been updated with a InputText to update and add this propterty to a movie.

### CODE REVIEW

**Comment by VanHamsteren** [comment]
Geen opmerkingen, ziet er goed uit!

**Review by vderlinden — APPROVED** [review]
Good. Thnx for the fast fix!

**Comment by vderlinden** [comment]
> Geen opmerkingen, ziet er goed uit!

Ook ff review achterlaten/approven dan aub.

**Review by SVrede — APPROVED** [review]
Ziet er goed uit! Wat mij betreft prima

**Pull request merged**
